// <auto-generated />

using System;
using System.Collections.Generic;

namespace Theraot.Facts
{
    public class Fact
    {        
        public static IEnumerable<Tuple<T>> Query<T>(FactCheckBase<T> check)
        {
            return check.GetTuples();
        }

        public static void Remove<T>(FactCheckBase<T> check)
        {
            var data = check.GetData();
            var fact = check.GetFact();
            if (data is IEnumerable<Tuple<T>>)
            {
                var toRemove = new List<Tuple<T>>(data as IEnumerable<Tuple<T>>);
                foreach(var tuple in toRemove)
                {
                    fact.Remove(tuple);
                }
            }
            if (data is IDictionary<int, Predicate<Tuple<T>>>)
            {
                var toRemove = new List<KeyValuePair<int, Predicate<Tuple<T>>>>(data as IDictionary<int, Predicate<Tuple<T>>>);
                foreach(var pair in toRemove)
                {
                    fact.Remove(pair.Key, pair.Value);
                }
            }
        }
        
        public static IEnumerable<Tuple<T1, T2>> Query<T1, T2>(FactCheckBase<T1, T2> check)
        {
            return check.GetTuples();
        }

        public static void Remove<T1, T2>(FactCheckBase<T1, T2> check)
        {
            var data = check.GetData();
            var fact = check.GetFact();
            if (data is IEnumerable<Tuple<T1, T2>>)
            {
                var toRemove = new List<Tuple<T1, T2>>(data as IEnumerable<Tuple<T1, T2>>);
                foreach(var tuple in toRemove)
                {
                    fact.Remove(tuple);
                }
            }
            if (data is IDictionary<int, Predicate<Tuple<T1, T2>>>)
            {
                var toRemove = new List<KeyValuePair<int, Predicate<Tuple<T1, T2>>>>(data as IDictionary<int, Predicate<Tuple<T1, T2>>>);
                foreach(var pair in toRemove)
                {
                    fact.Remove(pair.Key, pair.Value);
                }
            }
        }
        
        public static IEnumerable<Tuple<T1, T2, T3>> Query<T1, T2, T3>(FactCheckBase<T1, T2, T3> check)
        {
            return check.GetTuples();
        }

        public static void Remove<T1, T2, T3>(FactCheckBase<T1, T2, T3> check)
        {
            var data = check.GetData();
            var fact = check.GetFact();
            if (data is IEnumerable<Tuple<T1, T2, T3>>)
            {
                var toRemove = new List<Tuple<T1, T2, T3>>(data as IEnumerable<Tuple<T1, T2, T3>>);
                foreach(var tuple in toRemove)
                {
                    fact.Remove(tuple);
                }
            }
            if (data is IDictionary<int, Predicate<Tuple<T1, T2, T3>>>)
            {
                var toRemove = new List<KeyValuePair<int, Predicate<Tuple<T1, T2, T3>>>>(data as IDictionary<int, Predicate<Tuple<T1, T2, T3>>>);
                foreach(var pair in toRemove)
                {
                    fact.Remove(pair.Key, pair.Value);
                }
            }
        }
        
        public static IEnumerable<Tuple<T1, T2, T3, T4>> Query<T1, T2, T3, T4>(FactCheckBase<T1, T2, T3, T4> check)
        {
            return check.GetTuples();
        }

        public static void Remove<T1, T2, T3, T4>(FactCheckBase<T1, T2, T3, T4> check)
        {
            var data = check.GetData();
            var fact = check.GetFact();
            if (data is IEnumerable<Tuple<T1, T2, T3, T4>>)
            {
                var toRemove = new List<Tuple<T1, T2, T3, T4>>(data as IEnumerable<Tuple<T1, T2, T3, T4>>);
                foreach(var tuple in toRemove)
                {
                    fact.Remove(tuple);
                }
            }
            if (data is IDictionary<int, Predicate<Tuple<T1, T2, T3, T4>>>)
            {
                var toRemove = new List<KeyValuePair<int, Predicate<Tuple<T1, T2, T3, T4>>>>(data as IDictionary<int, Predicate<Tuple<T1, T2, T3, T4>>>);
                foreach(var pair in toRemove)
                {
                    fact.Remove(pair.Key, pair.Value);
                }
            }
        }
        
        public static IEnumerable<Tuple<T1, T2, T3, T4, T5>> Query<T1, T2, T3, T4, T5>(FactCheckBase<T1, T2, T3, T4, T5> check)
        {
            return check.GetTuples();
        }

        public static void Remove<T1, T2, T3, T4, T5>(FactCheckBase<T1, T2, T3, T4, T5> check)
        {
            var data = check.GetData();
            var fact = check.GetFact();
            if (data is IEnumerable<Tuple<T1, T2, T3, T4, T5>>)
            {
                var toRemove = new List<Tuple<T1, T2, T3, T4, T5>>(data as IEnumerable<Tuple<T1, T2, T3, T4, T5>>);
                foreach(var tuple in toRemove)
                {
                    fact.Remove(tuple);
                }
            }
            if (data is IDictionary<int, Predicate<Tuple<T1, T2, T3, T4, T5>>>)
            {
                var toRemove = new List<KeyValuePair<int, Predicate<Tuple<T1, T2, T3, T4, T5>>>>(data as IDictionary<int, Predicate<Tuple<T1, T2, T3, T4, T5>>>);
                foreach(var pair in toRemove)
                {
                    fact.Remove(pair.Key, pair.Value);
                }
            }
        }
        
        public static IEnumerable<Tuple<T1, T2, T3, T4, T5, T6>> Query<T1, T2, T3, T4, T5, T6>(FactCheckBase<T1, T2, T3, T4, T5, T6> check)
        {
            return check.GetTuples();
        }

        public static void Remove<T1, T2, T3, T4, T5, T6>(FactCheckBase<T1, T2, T3, T4, T5, T6> check)
        {
            var data = check.GetData();
            var fact = check.GetFact();
            if (data is IEnumerable<Tuple<T1, T2, T3, T4, T5, T6>>)
            {
                var toRemove = new List<Tuple<T1, T2, T3, T4, T5, T6>>(data as IEnumerable<Tuple<T1, T2, T3, T4, T5, T6>>);
                foreach(var tuple in toRemove)
                {
                    fact.Remove(tuple);
                }
            }
            if (data is IDictionary<int, Predicate<Tuple<T1, T2, T3, T4, T5, T6>>>)
            {
                var toRemove = new List<KeyValuePair<int, Predicate<Tuple<T1, T2, T3, T4, T5, T6>>>>(data as IDictionary<int, Predicate<Tuple<T1, T2, T3, T4, T5, T6>>>);
                foreach(var pair in toRemove)
                {
                    fact.Remove(pair.Key, pair.Value);
                }
            }
        }
        
        public static IEnumerable<Tuple<T1, T2, T3, T4, T5, T6, T7>> Query<T1, T2, T3, T4, T5, T6, T7>(FactCheckBase<T1, T2, T3, T4, T5, T6, T7> check)
        {
            return check.GetTuples();
        }

        public static void Remove<T1, T2, T3, T4, T5, T6, T7>(FactCheckBase<T1, T2, T3, T4, T5, T6, T7> check)
        {
            var data = check.GetData();
            var fact = check.GetFact();
            if (data is IEnumerable<Tuple<T1, T2, T3, T4, T5, T6, T7>>)
            {
                var toRemove = new List<Tuple<T1, T2, T3, T4, T5, T6, T7>>(data as IEnumerable<Tuple<T1, T2, T3, T4, T5, T6, T7>>);
                foreach(var tuple in toRemove)
                {
                    fact.Remove(tuple);
                }
            }
            if (data is IDictionary<int, Predicate<Tuple<T1, T2, T3, T4, T5, T6, T7>>>)
            {
                var toRemove = new List<KeyValuePair<int, Predicate<Tuple<T1, T2, T3, T4, T5, T6, T7>>>>(data as IDictionary<int, Predicate<Tuple<T1, T2, T3, T4, T5, T6, T7>>>);
                foreach(var pair in toRemove)
                {
                    fact.Remove(pair.Key, pair.Value);
                }
            }
        }
    }
}