// <auto-generated />

namespace Theraot.Facts
{
    public interface IFactCheckBase<T>
    {

    }

    public interface IFactCheck<T, TTarget> : IFactCheckBase<T>
    {

    }
    public interface IFactCheckBase<T1, T2>
    {

    }

    public interface IFactCheck<T1, T2, TTarget> : IFactCheckBase<T1, T2>
    {

    }
    public interface IFactCheckBase<T1, T2, T3>
    {

    }

    public interface IFactCheck<T1, T2, T3, TTarget> : IFactCheckBase<T1, T2, T3>
    {

    }
    public interface IFactCheckBase<T1, T2, T3, T4>
    {

    }

    public interface IFactCheck<T1, T2, T3, T4, TTarget> : IFactCheckBase<T1, T2, T3, T4>
    {

    }
    public interface IFactCheckBase<T1, T2, T3, T4, T5>
    {

    }

    public interface IFactCheck<T1, T2, T3, T4, T5, TTarget> : IFactCheckBase<T1, T2, T3, T4, T5>
    {

    }
    public interface IFactCheckBase<T1, T2, T3, T4, T5, T6>
    {

    }

    public interface IFactCheck<T1, T2, T3, T4, T5, T6, TTarget> : IFactCheckBase<T1, T2, T3, T4, T5, T6>
    {

    }
    public interface IFactCheckBase<T1, T2, T3, T4, T5, T6, T7>
    {

    }

    public interface IFactCheck<T1, T2, T3, T4, T5, T6, T7, TTarget> : IFactCheckBase<T1, T2, T3, T4, T5, T6, T7>
    {

    }
}